Fix multiline formatting bug
st--/annotate-equations pull request #11
Opened 2023-01-20 00:18 UTC by vleni

2023-01-20 04:57 UTC, vleni commented
This branch replaces `\eqnannotationtext` with `\eqnannotationfont` and `\eqnannotationstrut` with the font part provided to `\node[font=\eqnannotationfont]`. I have not completely modified the example and PDF yet in order to showcase that it works as intended.

2023-01-20 07:02 UTC, st-- commented
Great, thank you so much for contributing - I'll see how it works :)

2023-02-08 12:54 UTC, st-- commented
Just to let you know I'm still intending to sort this out!

2023-02-08 17:41 UTC, vleni commented
I'll try to produce an example of this, but here is a solution with minipage: https://tex.stackexchange.com/questions/30734/how-make-sure-two-elements-stay-on-the-same-page

I don't know if there is a programmatic way to do it without user intervention though, since tikz is unaware of whether a page flip has happened.

If you can put `\annotate` commands in `\[ ... \]` environments it might solve the issue

2023-02-14 08:28 UTC, st-- requested changes
Hi @vleni ! Thank you so much for fixing this issue. This is basically good to go, I just marked a few changes, mainly for consistency - most of it as review suggestions, so you could just go and accept them from GitHub. The only other thing I couldn't "suggest" directly was removing the now-obsolete workaround - I've left a comment about that.

If you're happy with my suggestions, ping me and I'll merge it in. :)

2023-02-14 08:28 UTC, st-- commented on annotate-equations.sty
> +			font=\eqnannotationfont]  % color blended with white to 85%, any (optional) extra args #1
```suggestion
		\node[anchor=\swapNorthSouth{\EAmarkanchor},color=\myEAcolor!85,font=\eqnannotationfont,
			#1]  % color blended with white to 85%, any (optional) extra args #1
```
the `#1` should be last so the user can override previously set options

2023-02-14 08:28 UTC, st-- commented on annotate-equations.tex
> +\texttt{font} field of tikz and can be used to have consistent formatting:
```suggestion
\texttt{font} field of TikZ and can be used to have consistent formatting:
```

2023-02-14 08:28 UTC, st-- commented on annotate-equations.tex
> +from text to the surrounding diagrams. By default it is \verb|\strut|, which has
```suggestion
\verb|\eqnannotationstrut| is defined to be a strut (zero-width height) to provide minimum distance between the text and the corresponding arrow line. By default it is \verb|\strut|, which has
```

2023-02-14 08:28 UTC, st-- commented on annotate-equations.tex
> +\annotate[yshift=-0.5em]{below}{v}{velocity}
```suggestion
    \eqnmarkbox[blue]{size}{s}
\end{equation*}
\annotate[yshift=-0.5em]{below}{size}{the size}
```
I think the effect is more striking with text that doesn't have descenders (like in `y`).
also, changed the tab to spaces for consistency with the rest of the formatting.

2023-02-14 08:28 UTC, st-- commented on annotate-equations.tex
> +\renewcommand{\eqnannotationstrut}{\strut}
```suggestion
\renewcommand{\eqnannotationstrut}{\strut}  % package default
```
for consistency

2023-02-14 08:28 UTC, st-- commented on annotate-equations.tex
> +	\vspace{1em}
```suggestion
\renewcommand{\eqnannotationstrut}{}
\begin{equation*}
    \eqnmarkbox[blue]{size}{s}
\end{equation*}
\annotate[yshift=-0.5em]{below}{size}{the size}
\vspace{1em}
```
in line with above

2023-02-14 08:28 UTC, st-- commented on annotate-equations.tex
> +\noindent
I don't think this is necessary here (at the end of a section)?
```suggestion
\noindent
```

2023-02-14 08:28 UTC, st-- commented on annotate-equations.tex
> -    \item Formatting only covers first line in multi-line annotation texts (see \cref{sec:multiline}).
Thanks for fixing it :tada:

2023-02-14 08:28 UTC, st-- commented on annotate-equations.tex
> +Here is a manual work-around: (obsolete)
I don't think it's helpful to show the old work-around - could you just delete it instead? All it needs to say here is that using `\\` within the text to get a line break works just fine.:)

2023-02-14 08:30 UTC, vleni commented
Thanks! It should be ok now after your change.

2023-02-14 12:56 UTC, st-- commented
@vleni if you agree with all the suggestions, you can just go and accept them (see [GitHub docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) in case that's new to you).

Also, would you be happy to adapt the no-longer-needed section on the workaround (see https://github.com/st--/annotate-equations/pull/11/files#r1105454093) instead of just marking it "obsolete"?

If you prefer, I can also do all those changes myself, but I didn't want to do so without giving you the chance first because it would seem rude to me to edit someone else's contributions for them:)

2023-02-14 12:58 UTC, st-- commented
(Side note- I edited the PR description to include "resolves #2" because a) the link to the issue makes it easier to keep up with why this PR is here and what it does and b) GitHub has [this neat feature](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) where merging a PR also closes the linked issues :))

2023-02-14 13:00 UTC, st-- commented
Oh, one more task: after the final changes, could you also regenerate the PDF & commit that?

_Update:_ I spotted a minor typography issue in the TeX that I fixed on the `main` branch - you can either merge that into your branch and then regenerate the PDF, or skip generating the PDF & I'll do it separately after merging your PR - either works:)

2023-02-14 17:14 UTC, lenianiva commented
ok I fixed all of the suggestions and I regenerated the PDF but I didn't merge master. Could you do it in the merge commit?

2023-02-15 16:11 UTC, st-- reviewed
looks good!

2023-02-15 16:11 UTC, st-- commented on annotate-equations.tex
> +\texttt{font} field of TikZ and can be used to have consistent formatting:
```suggestion
\verb|\eqnannotationfont| sets the \texttt{font} field of the TikZ annotation label and can be re-set to change its formatting:
```

2023-02-15 16:11 UTC, st-- commented on annotate-equations.tex
> +default it is \verb|\strut|, which has, which has a similar effect to
```suggestion
default it is \verb|\strut|, which has a similar effect to
```

2023-02-15 16:14 UTC, merged